parameters:
#    hursit_blog.example.class: Hursit\BlogBundle\Example

services:
#    hursit_blog.example:
#        class: %hursit_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
