<?php

namespace Hursit\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getNews($limit){
        return $query = $this->findAll();
        
    }
    public function getAllPosts(){
        
    }
}
